name: prod_software_rutinator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  splashify: ^0.0.3
  sqflite: ^2.3.3+1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/RutinatorIcon.png"
  min_sdk_android: 16 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/brawlAssets/
    - assets/CCAssets/
    - assets/CRAssets/
    - assets/SBAssets/
  fonts:
    - family: brawl
      fonts:
        - asset: assets/fonts/Nougat-ExtraBlack.ttf
    - family: clash
      fonts:
        - asset: assets/fonts/supercell-magic.ttf
    - family : squad
      fonts:
        - asset: assets/fonts/SquadLatin-Black.otf
